### ISSUE TITLE
Window sensor would be fine. 

### ISSUE THREAD

**Issue by Sillec123** [dolfje/be.uwsoftware.maxcube#1]
Hey, thanks for the App. It would be awesome if you could add the sensors. And openhab is using a exclusive mode. Is this also included?

**Comment by dolfje** [comment]
The system keeps the connection open for 2s. So if you set the refreshInterval lower than 2s, it will behave like exclusive mode.

I want to add the window sensor, but I don't have any. So I will need testers for this as I cannot test myself.

**Comment by Sillec123** [comment]
I would test it for you. 

Diese E-Mail wurde von einem mobilen Gerät gesendet. Ich bitte Tippfehler zu entschuldigen.

This mail was written on a mobile device. Thank you for understanding.

**Comment by dolfje** [comment]
The window door sensor has been added and can be tested. Please keep me posted about any issues.

**Comment by Sillec123** [comment]
The app says no window sensor found. Do you need any logs?
I used the beta

Diese E-Mail wurde von einem mobilen Gerät gesendet. Ich bitte Tippfehler zu entschuldigen.

This mail was written on a mobile device. Thank you for understanding.

**Comment by dolfje** [comment]
Okay, that is strange. We will have to debug.
I have created a new branch 'window_switch_testing'. 

Do you run the app by doing 'athom app run'? Please do so for this one time.
Then you will see debug information appear. It should print out 'Device type'. Can you send that over to me?

**Comment by Sillec123** [comment]
b36ede5f73c7591963ca74&app=be.uwsoftware.maxcube
─────────────── Logging stdout & stderr ───────────────
2019-01-04 11:44:34 [log] [MyApp] MaxCube is running...
2019-01-04 11:44:35 [log] [ManagerDrivers] [max] [0] device init
2019-01-04 11:44:35 [log] [ManagerDrivers] [max] [1] device init
2019-01-04 11:44:35 [log] [ManagerDrivers] [max] [2] device init
2019-01-04 11:44:35 [log] [ManagerDrivers] [max] [3] device init
2019-01-04 11:44:35 [log] [ManagerDrivers] [max] [4] device init
2019-01-04 11:44:35 [log] [ManagerDrivers] [max] [5] device init
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 6
2019-01-04 11:44:36 [log] [ManagerDrivers] [max] [0] poll
2019-01-04 11:44:36 [log] [ManagerDrivers] [max] [0] refresh data
2019-01-04 11:44:36 [log] [ManagerDrivers] [max] [1] poll
2019-01-04 11:44:36 [log] [ManagerDrivers] [max] [1] refresh data
2019-01-04 11:44:36 [log] [ManagerDrivers] [max] [2] poll
2019-01-04 11:44:36 [log] [ManagerDrivers] [max] [2] refresh data
2019-01-04 11:44:36 [log] [ManagerDrivers] [max] [3] poll
2019-01-04 11:44:36 [log] [ManagerDrivers] [max] [3] refresh data
2019-01-04 11:44:36 [log] [ManagerDrivers] [max] [4] poll
2019-01-04 11:44:36 [log] [ManagerDrivers] [max] [4] refresh data
2019-01-04 11:44:36 [log] [ManagerDrivers] [max] [5] poll
2019-01-04 11:44:36 [log] [ManagerDrivers] [max] [5] refresh data
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 6

**Comment by dolfje** [comment]
Thank you.
Can you retest and again give me the output?

**Comment by Sillec123** [comment]
Sure:

2019-01-04 12:02:46 [log] [MyApp] MaxCube is running...
2019-01-04 12:02:47 [log] [ManagerDrivers] [max] [0] device init
2019-01-04 12:02:47 [log] [ManagerDrivers] [max] [1] device init
2019-01-04 12:02:47 [log] [ManagerDrivers] [max] [2] device init
2019-01-04 12:02:47 [log] [ManagerDrivers] [max] [3] device init
2019-01-04 12:02:47 [log] [ManagerDrivers] [max] [4] device init
2019-01-04 12:02:47 [log] [ManagerDrivers] [max] [5] device init
{ '146927': 
   { device_type: 1,
     rf_address: '146927',
     serialnumber: 'MEQ1776506',
     device_name: 'Thermostat_Kitchen',
     room_id: 4 },
  '189511': 
   { device_type: 4,
     rf_address: '189511',
     serialnumber: 'OEQ0911290',
     device_name: 'Fensterkontakt_Kitchen',
     room_id: 4 },
  '0a936a': 
   { device_type: 4,
     rf_address: '0a936a',
     serialnumber: 'KEQ0472390',
     device_name: 'Fensterkontakt 1',
     room_id: 1 },
  '13f415': 
   { device_type: 1,
     rf_address: '13f415',
     serialnumber: 'MEQ1453203',
     device_name: 'Thermostat 1',
     room_id: 1 },
  '13efa5': 
   { device_type: 1,
     rf_address: '13efa5',
     serialnumber: 'MEQ1451174',
     device_name: 'Thermostat 1',
     room_id: 2 },
  '13ef67': 
   { device_type: 1,
     rf_address: '13ef67',
     serialnumber: 'MEQ1451110',
     device_name: 'Thermostat 1',
     room_id: 3 },
  '09829b': 
   { device_type: 5,
     rf_address: '09829b',
     serialnumber: 'KEQ0521324',
     device_name: 'Eco Taster 1',
     room_id: 0 },
  '189e91': 
   { device_type: 4,
     rf_address: '189e91',
     serialnumber: 'OEQ0913235',
     device_name: 'Fensterkontakt links',
     room_id: 2 },
  '146a35': 
   { device_type: 1,
     rf_address: '146a35',
     serialnumber: 'MEQ1776764',
     device_name: 'Thermostat_office',
     room_id: 5 },
  '189ca4': 
   { device_type: 4,
     rf_address: '189ca4',
     serialnumber: 'OEQ0912806',
     device_name: 'Fensterkontakt_Office',
     room_id: 5 },
  '15704e': 
   { device_type: 4,
     rf_address: '15704e',
     serialnumber: 'NEQ0853695',
     device_name: 'Fensterkontakt_Flur',
     room_id: 6 },
  '146c71': 
   { device_type: 1,
     rf_address: '146c71',
     serialnumber: 'MEQ1777400',
     device_name: 'Thermostat 1',
     room_id: 6 } }
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 6
2019-01-04 12:02:47 [log] [ManagerDrivers] [max] [0] poll
2019-01-04 12:02:47 [log] [ManagerDrivers] [max] [0] refresh data
2019-01-04 12:02:47 [log] [ManagerDrivers] [max] [1] poll
2019-01-04 12:02:47 [log] [ManagerDrivers] [max] [1] refresh data
2019-01-04 12:02:47 [log] [ManagerDrivers] [max] [2] poll
2019-01-04 12:02:47 [log] [ManagerDrivers] [max] [2] refresh data
2019-01-04 12:02:47 [log] [ManagerDrivers] [max] [3] poll
2019-01-04 12:02:48 [log] [ManagerDrivers] [max] [3] refresh data
2019-01-04 12:02:48 [log] [ManagerDrivers] [max] [4] poll
2019-01-04 12:02:48 [log] [ManagerDrivers] [max] [4] refresh data
2019-01-04 12:02:48 [log] [ManagerDrivers] [max] [5] poll
2019-01-04 12:02:48 [log] [ManagerDrivers] [max] [5] refresh data
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 6
{ '146927': 
   { device_type: 1,
     rf_address: '146927',
     serialnumber: 'MEQ1776506',
     device_name: 'Thermostat_Kitchen',
     room_id: 4 },
  '189511': 
   { device_type: 4,
     rf_address: '189511',
     serialnumber: 'OEQ0911290',
     device_name: 'Fensterkontakt_Kitchen',
     room_id: 4 },
  '0a936a': 
   { device_type: 4,
     rf_address: '0a936a',
     serialnumber: 'KEQ0472390',
     device_name: 'Fensterkontakt 1',
     room_id: 1 },
  '13f415': 
   { device_type: 1,
     rf_address: '13f415',
     serialnumber: 'MEQ1453203',
     device_name: 'Thermostat 1',
     room_id: 1 },
  '13efa5': 
   { device_type: 1,
     rf_address: '13efa5',
     serialnumber: 'MEQ1451174',
     device_name: 'Thermostat 1',
     room_id: 2 },
  '13ef67': 
   { device_type: 1,
     rf_address: '13ef67',
     serialnumber: 'MEQ1451110',
     device_name: 'Thermostat 1',
     room_id: 3 },
  '09829b': 
   { device_type: 5,
     rf_address: '09829b',
     serialnumber: 'KEQ0521324',
     device_name: 'Eco Taster 1',
     room_id: 0 },
  '189e91': 
   { device_type: 4,
     rf_address: '189e91',
     serialnumber: 'OEQ0913235',
     device_name: 'Fensterkontakt links',
     room_id: 2 },
  '146a35': 
   { device_type: 1,
     rf_address: '146a35',
     serialnumber: 'MEQ1776764',
     device_name: 'Thermostat_office',
     room_id: 5 },
  '189ca4': 
   { device_type: 4,
     rf_address: '189ca4',
     serialnumber: 'OEQ0912806',
     device_name: 'Fensterkontakt_Office',
     room_id: 5 },
  '15704e': 
   { device_type: 4,
     rf_address: '15704e',
     serialnumber: 'NEQ0853695',
     device_name: 'Fensterkontakt_Flur',
     room_id: 6 },
  '146c71': 
   { device_type: 1,
     rf_address: '146c71',
     serialnumber: 'MEQ1777400',
     device_name: 'Thermostat 1',
     room_id: 6 } }
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 6
Device asked 1
Device asked 4
Device asked 4
Device asked 1
Device asked 1
Device asked 1
Device asked 5
Device asked 4
Device asked 1
Device asked 4
Device asked 4
Device asked 1

**Comment by dolfje** [comment]
Hey,

And does it already work?
Or does they still don't appear?

Nikos

*USW*
Nikos Verschore
nikos@uwsoftware.be
http://uwsoftware.be
+32(0)476/29.36.64

**Comment by Sillec123** [comment]
Same issue! No devices found!  (Sensor)

**Comment by Sillec123** [comment]
2019-01-04 14:51:21 [log] [MyApp] MaxCube is running...
{ '146927': 
   { device_type: 1,
     rf_address: '146927',
     serialnumber: 'MEQ1776506',
     device_name: 'Thermostat_Kitchen',
     room_id: 4 },
  '189511': 
   { device_type: 4,
     rf_address: '189511',
     serialnumber: 'OEQ0911290',
     device_name: 'Fensterkontakt_Kitchen',
     room_id: 4 },
  '0a936a': 
   { device_type: 4,
     rf_address: '0a936a',
     serialnumber: 'KEQ0472390',
     device_name: 'Fensterkontakt 1',
     room_id: 1 },
  '13f415': 
   { device_type: 1,
     rf_address: '13f415',
     serialnumber: 'MEQ1453203',
     device_name: 'Thermostat 1',
     room_id: 1 },
  '13efa5': 
   { device_type: 1,
     rf_address: '13efa5',
     serialnumber: 'MEQ1451174',
     device_name: 'Thermostat 1',
     room_id: 2 },
  '13ef67': 
   { device_type: 1,
     rf_address: '13ef67',
     serialnumber: 'MEQ1451110',
     device_name: 'Thermostat 1',
     room_id: 3 },
  '09829b': 
   { device_type: 5,
     rf_address: '09829b',
     serialnumber: 'KEQ0521324',
     device_name: 'Eco Taster 1',
     room_id: 0 },
  '189e91': 
   { device_type: 4,
     rf_address: '189e91',
     serialnumber: 'OEQ0913235',
     device_name: 'Fensterkontakt links',
     room_id: 2 },
  '146a35': 
   { device_type: 1,
     rf_address: '146a35',
     serialnumber: 'MEQ1776764',
     device_name: 'Thermostat_office',
     room_id: 5 },
  '189ca4': 
   { device_type: 4,
     rf_address: '189ca4',
     serialnumber: 'OEQ0912806',
     device_name: 'Fensterkontakt_Office',
     room_id: 5 },
  '15704e': 
   { device_type: 4,
     rf_address: '15704e',
     serialnumber: 'NEQ0853695',
     device_name: 'Fensterkontakt_Flur',
     room_id: 6 },
  '146c71': 
   { device_type: 1,
     rf_address: '146c71',
     serialnumber: 'MEQ1777400',
     device_name: 'Thermostat 1',
     room_id: 6 } }
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 6
Device asked 1
Device asked 4
Device asked 4
Device asked 1
Device asked 1
Device asked 1
Device asked 5
Device asked 4
Device asked 1
Device asked 4
Device asked 4
Device asked 1
{ '146927': 
   { device_type: 1,
     rf_address: '146927',
     serialnumber: 'MEQ1776506',
     device_name: 'Thermostat_Kitchen',
     room_id: 4 },
  '189511': 
   { device_type: 4,
     rf_address: '189511',
     serialnumber: 'OEQ0911290',
     device_name: 'Fensterkontakt_Kitchen',
     room_id: 4 },
  '0a936a': 
   { device_type: 4,
     rf_address: '0a936a',
     serialnumber: 'KEQ0472390',
     device_name: 'Fensterkontakt 1',
     room_id: 1 },
  '13f415': 
   { device_type: 1,
     rf_address: '13f415',
     serialnumber: 'MEQ1453203',
     device_name: 'Thermostat 1',
     room_id: 1 },
  '13efa5': 
   { device_type: 1,
     rf_address: '13efa5',
     serialnumber: 'MEQ1451174',
     device_name: 'Thermostat 1',
     room_id: 2 },
  '13ef67': 
   { device_type: 1,
     rf_address: '13ef67',
     serialnumber: 'MEQ1451110',
     device_name: 'Thermostat 1',
     room_id: 3 },
  '09829b': 
   { device_type: 5,
     rf_address: '09829b',
     serialnumber: 'KEQ0521324',
     device_name: 'Eco Taster 1',
     room_id: 0 },
  '189e91': 
   { device_type: 4,
     rf_address: '189e91',
     serialnumber: 'OEQ0913235',
     device_name: 'Fensterkontakt links',
     room_id: 2 },
  '146a35': 
   { device_type: 1,
     rf_address: '146a35',
     serialnumber: 'MEQ1776764',
     device_name: 'Thermostat_office',
     room_id: 5 },
  '189ca4': 
   { device_type: 4,
     rf_address: '189ca4',
     serialnumber: 'OEQ0912806',
     device_name: 'Fensterkontakt_Office',
     room_id: 5 },
  '15704e': 
   { device_type: 4,
     rf_address: '15704e',
     serialnumber: 'NEQ0853695',
     device_name: 'Fensterkontakt_Flur',
     room_id: 6 },
  '146c71': 
   { device_type: 1,
     rf_address: '146c71',
     serialnumber: 'MEQ1777400',
     device_name: 'Thermostat 1',
     room_id: 6 } }
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 6
{ '146927': 
   { device_type: 1,
     rf_address: '146927',
     serialnumber: 'MEQ1776506',
     device_name: 'Thermostat_Kitchen',
     room_id: 4 },
  '189511': 
   { device_type: 4,
     rf_address: '189511',
     serialnumber: 'OEQ0911290',
     device_name: 'Fensterkontakt_Kitchen',
     room_id: 4 },
  '0a936a': 
   { device_type: 4,
     rf_address: '0a936a',
     serialnumber: 'KEQ0472390',
     device_name: 'Fensterkontakt 1',
     room_id: 1 },
  '13f415': 
   { device_type: 1,
     rf_address: '13f415',
     serialnumber: 'MEQ1453203',
     device_name: 'Thermostat 1',
     room_id: 1 },
  '13efa5': 
   { device_type: 1,
     rf_address: '13efa5',
     serialnumber: 'MEQ1451174',
     device_name: 'Thermostat 1',
     room_id: 2 },
  '13ef67': 
   { device_type: 1,
     rf_address: '13ef67',
     serialnumber: 'MEQ1451110',
     device_name: 'Thermostat 1',
     room_id: 3 },
  '09829b': 
   { device_type: 5,
     rf_address: '09829b',
     serialnumber: 'KEQ0521324',
     device_name: 'Eco Taster 1',
     room_id: 0 },
  '189e91': 
   { device_type: 4,
     rf_address: '189e91',
     serialnumber: 'OEQ0913235',
     device_name: 'Fensterkontakt links',
     room_id: 2 },
  '146a35': 
   { device_type: 1,
     rf_address: '146a35',
     serialnumber: 'MEQ1776764',
     device_name: 'Thermostat_office',
     room_id: 5 },
  '189ca4': 
   { device_type: 4,
     rf_address: '189ca4',
     serialnumber: 'OEQ0912806',
     device_name: 'Fensterkontakt_Office',
     room_id: 5 },
  '15704e': 
   { device_type: 4,
     rf_address: '15704e',
     serialnumber: 'NEQ0853695',
     device_name: 'Fensterkontakt_Flur',
     room_id: 6 },
  '146c71': 
   { device_type: 1,
     rf_address: '146c71',
     serialnumber: 'MEQ1777400',
     device_name: 'Thermostat 1',
     room_id: 6 } }
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 11
Device type: 11
Device type: 6
Device type: 6
Device type: 6
Device asked 1
Device asked 4
Device asked 4
Device asked 1
Device asked 1
Device asked 1
Device asked 5
Device asked 4
Device asked 1
Device asked 4
Device asked 4
Device asked 1


The icons are still a rocket?!

**Comment by dolfje** [comment]
Okay,
I stilll had a typo in the files

Check again, it normally should work. I'm very curious if the open/close
state will be good.

Yes, the icons are still a rocket. Only the real images has changed (for in
the homey app store).
Rest comes later.

Nikos

*USW*
Nikos Verschore
nikos@uwsoftware.be
http://uwsoftware.be
+32(0)476/29.36.64

**Comment by Sillec123** [comment]
Now i can add the sensors! Great! That means, i can install this version? Or should i wait?

**Comment by dolfje** [comment]
You can install this version. Please also test if the state is changed when
opening and closing.
Maybe best to set the refresh time to something like 1 or 2s (and restart
app).

develop and master also have the required changed.

Nikos

*USW*
Nikos Verschore
nikos@uwsoftware.be
http://uwsoftware.be
+32(0)476/29.36.64

**Comment by Sillec123** [comment]
It works! The status is correct.

**Comment by dolfje** [comment]
Perfect! Keep me in the loop if you find other issues.
